// <auto-generated />
namespace EasyMaintain.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Chnages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chnages));
        
        string IMigrationMetadata.Id
        {
            get { return "201610070857018_Chnages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
