//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMaintain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftModel
    {
        public AircraftModel()
        {
            this.SparePart_AircraftModel = new HashSet<SparePart_AircraftModel>();
        }
    
        public int AircraftModelID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> EngineTypeID { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string AdditionalData { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<SparePart_AircraftModel> SparePart_AircraftModel { get; set; }
    }
}
