//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMaintain.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyMaintainEntities : DbContext
    {
        public EasyMaintainEntities()
            : base("name=EasyMaintainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AircraftModel> AircraftModels { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<EngineType> EngineTypes { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<SparePart_AircraftModel> SparePart_AircraftModel { get; set; }
        public virtual DbSet<SparePart_Manufacturer> SparePart_Manufacturer { get; set; }
        public virtual DbSet<SparePart_Supplier> SparePart_Supplier { get; set; }
        public virtual DbSet<SparePart> SpareParts { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
