//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMaintain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineType
    {
        public EngineType()
        {
            this.AircraftModels = new HashSet<AircraftModel>();
        }
    
        public int EngineTypeID { get; set; }
        public string EngineTypeName { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string AdditionalData { get; set; }
    
        public virtual ICollection<AircraftModel> AircraftModels { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
