//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMaintain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public Nullable<int> SparePartID { get; set; }
        public string UnitToMeasure { get; set; }
        public Nullable<decimal> ItemsInStock { get; set; }
        public Nullable<System.DateTime> LastPurchasedDate { get; set; }
        public Nullable<int> RefillTriggerQty { get; set; }
        public string StoreLocation { get; set; }
        public string AdditionalData { get; set; }
    
        public virtual SparePart SparePart { get; set; }
    }
}
