//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMaintain.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.AircraftModels = new HashSet<AircraftModel>();
            this.EngineTypes = new HashSet<EngineType>();
            this.SparePart_Manufacturer = new HashSet<SparePart_Manufacturer>();
        }
    
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public string Description { get; set; }
        public string AdditionalData { get; set; }
    
        public virtual ICollection<AircraftModel> AircraftModels { get; set; }
        public virtual ICollection<EngineType> EngineTypes { get; set; }
        public virtual ICollection<SparePart_Manufacturer> SparePart_Manufacturer { get; set; }
    }
}
